---
title: "Testing"
author: "Freddy Drennan"
date: "4/28/2019"
output: html_document
---

```{r setup, include=FALSE}
library(awsR)
library(tidyverse)
```

```{r, eval = FALSE}
library(awsR)
# system("virtualenv -p /usr/bin/python3 /home/ubuntu/.virtualenvs/py3-virtualenv")
# Also works with this
#virtualenv_create("py3-virtualenv", python = "/usr/bin/python3")
# use_virtualenv("py3-virtualenv")
# install_python(envname = "py3-virtualenv")

```

```{r, message=FALSE, warning=FALSE}
ec2 <- 
  boto$client("ec2")
```

```{r}
ec2$describe_addresses(
  Filters = list(list(Name = "domain", Values = list("vpc")))
) %>% 
  map(
     function(x){
       map(x, function(x){
         enframe(x)
       })
     }
)
```

```{r}
# key_pair <- client_ec2()$create_key_pair(KeyName='foo')
# 
# write.table(key_pair$KeyMaterial,
#             file = 'foo.pem',
#             row.names = FALSE, 
#             col.names = FALSE, 
#             quote = FALSE)
```

```{bash}
<!-- chmod 400 foo.pem -->
```

```{r}
server <- 
  ec2_instance_create(ImageId = 'ami-0c55b159cbfafe1f0',
                      KeyName = 'foo',
                      InstanceType = 't2.large',
                      InstanceStorage = 50,
                      postgres_password = 'mypassword',
                      phone_number = 7654326236,
                      DeviceName = "/dev/sda1",
                      user_data = NA)
```

```{r}
ec2_info <- ec2_get_info() %>% 
  # filter(state == 'running') %>% 
  filter(launch_time == max(launch_time),
         public_ip_address != '18.217.102.18') 


ec2_info$public_ip_address %>% 
  str_replace_all('\\.', '\\-') %>% 
  paste0('ssh -i "foo.pem" ubuntu@ec2-', ., '.us-east-2.compute.amazonaws.com', collapse = "") %>% 
  paste("Please enter the follwing into your terminal", 
        ., 
        'Then type on the remote server to set your password: sudo passwd ubuntu',
        paste0('Login with the username ubuntu with the password you just set at RStudio Server: ', ec2_info$public_ip_address,  ":8787"),
        sep = "\n") %>% 
  message

```

```{r}
library(RPostgreSQL)
library(tidyverse)
library(dbplyr)
library(lubridate)
library(DBI)

con <- dbConnect(PostgreSQL(),
                 # dbname   = 'linkedin',
                 host     = ec2_info$public_ip_address,
                 port     = 5432,
                 user     = "postgres",
                 password = "mypassword")


```


```{r}
for(i in files) {
  print(i)
  cone = read_csv(files[[1]])
  dbWriteTable(con, 'library', cone, append = TRUE)
}


mtcars_data <-
  tbl(con, in_schema('public', 'mtcars'))
```

```{r}
head(mtcars_data) %>% collect()
```


```{r}
ec2_instance_stop(ids = ec2_info$instance_id, terminate = TRUE)
```

```{r}
client$modify_instance_attribute(InstanceId=ec2_info$instance_id, 
                                 Attribute='instanceType',
                                 Value='t2.small')

client$start_instances(InstanceIds = list(ec2_info$instance_id))
```
